name: .NET Release

on:
  push:
    tags: [ "v*" ]
  pull_request:
    tags: [ "v*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run: dotnet publish -c Release --no-self-contained

    - name: Pack
      run: dotnet pack -c Release

    - name: Push the package to GPR
      run: dotnet nuget push src/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://nuget.pkg.github.com/stcmz/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the package to nuget.org
      run: dotnet nuget push src/bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Release Note

          Please refer to the commit messages for what's new in this release. This library is also available on Github Package Registry (GPR) and NuGet(https://www.nuget.org/packages/Mozo.Fwob/${{ github.ref }}).

          ### Prerequisite

          * .NET 7.0 SDK or runtime: Follow [the official guide](https://dotnet.microsoft.com/download/dotnet/7.0) to install.
        draft: false
        prerelease: false
