name: .NET Release

on:
  push:
    tags: [ "v*" ]
  pull_request:
    tags: [ "v*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura

    - name: Publish for .NET Standard 2.0
      run: dotnet publish src -c Release -f netstandard2.0 --no-self-contained

    - name: Publish for .NET Framework 4.8
      run: dotnet publish src -c Release -f net48 --no-self-contained

    - name: Publish for .NET 7.0
      run: dotnet publish src -c Release -f net7.0 --no-self-contained

    - name: Pack
      run: dotnet pack -c Release

    - name: Push the package to GPR
      run: dotnet nuget push src/bin/Release/*.nupkg --skip-duplicate -k $NUGET_AUTH_TOKEN -s https://nuget.pkg.github.com/stcmz/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the package to nuget.org
      run: dotnet nuget push src/bin/Release/*.nupkg --skip-duplicate -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Release Note

          Please refer to the commit messages for what's new in this release. This library is also available on [Github Package Registry (GPR)](https://github.com/stcmz/Mozo.Fwob/pkgs/nuget/Mozo.Fwob) and [NuGet](https://www.nuget.org/packages/Mozo.Fwob/${{ steps.get_version.outputs.version }}).

          ### Prerequisite

          * .NET 7.0 SDK or runtime: Follow [the official guide](https://dotnet.microsoft.com/download/dotnet/7.0) to install.
        draft: false
        prerelease: false
